### PR TITLE
Support Swift 3.0

### PR DESCRIPTION
**Pull request by danthorpe**

### CODE REVIEW

**Comment by danthorpe** [comment]
Unfortunately, this conversion to Swift 3.0 crashes the compiler. Radar number: 27018457

**Comment by simme** [comment]
Any idea what might be wrong? I tried looking at the source (which is very small :)) and commenting things out. I can get it to build, but only if I remove all of the three methods on the `CodingType` extension and the uses of those in the `ValueCoding` extension.

So not very helpful I'm afraid.

**Comment by danthorpe** [comment]
@simme I've got no idea unfortunately. I did submit a Radar for it. Did you try with beta 2? I'm hoping we get a beta 3 on Tuesday which might change things.

**Comment by simme** [comment]
Yeah, I'm running beta 2.

And I was so stoked to finally convert my project to Swift 3. I was not ready for some silly compiler bug to stop me!

**Comment by simme** [comment]
Might've found something! Removing the `ValueType.Coder == Self` constraint on the `CodingType` extension makes the project build and the tests pass! Although, this might of course lead to other weirdness?

**Comment by danthorpe** [comment]
Yeah, I'm sorry - I will hopefully get another chance to look at it this over the weekend and possibly get a more helpful error message. You could report a Bug with  too though.

**Comment by danthorpe** [comment]
Yeah, that could lead to other issues - because we basically have to make sure that Foo.Coder.ValueType == Foo etc

**Comment by simme** [comment]
Right. At least it seems like its the recursive protocol thing that might be the issue. Maybe information that could help the people looking at the radars? :)

**Comment by danthorpe** [comment]
Yep - definitely. I'll update the Radar.

**Comment by danthorpe** [comment]
@simme is there any chance you could try this branch using Swift master/HEAD? Then we can see if it's an issue that's already been fixed. If you can't I can try - but might not have time to update my local Swift environment this weekend.

**Comment by danthorpe** [comment]
An update here - still fails on latest Swift development snapshot.

**Comment by danthorpe** [comment]
@simme this is now working. Please let me know if you have any issues. You will need to integrate by pointing to the `swift/3.0` branch.

**Comment by simme** [comment]
Just got around to reading this.

So basically you've removed the `ValueType.Coder == Self` constraint on the `CodingType` extension? The rest of the changes seem to be pretty much only renaming related.

It's awesome to have a compiling thing to point Carthage too though! Hoping we can get that compile time safety back before 3.0 is out there though!

**Comment by danthorpe** [comment]
I've removed the whole internal API on `CoderType` and done everything inside the public extensions on `ValueType` - so still compile time safe. And less code!

**Comment by simme** [comment]
Ah, of course. I only read through one of the commits!

Nice work! Gonna try it out.

**Pull request closed without merging**
